# Generated by Django 5.2 on 2025-10-09 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('blog_img', models.ImageField(blank=True, null=True, upload_to='blogImg/')),
                ('blog_type', models.CharField(choices=[('SPORTS', 'SPORTS'), ('TRAVEL', 'TRAVEL'), ('POLTICIS', 'POLITICS'), ('NATIONAL BLOG', 'NATIONAL BLOG')], max_length=18)),
            ],
        ),
    ]
