# Generated by Django 5.2 on 2025-10-09 03:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='blogs',
            name='updated_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
