# Generated by Django 5.2 on 2025-10-09 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_blogs_created_at_blogs_updated_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='blog_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
